# ───────────────
# Builder Stage
# ───────────────
FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

# ───────────────
# Runtime Stage
# ───────────────
FROM node:22-slim

WORKDIR /app

COPY --from=builder /app .

ENV IMAGE_TYPE="Multi-Stage Slim"

EXPOSE 3000

CMD ["npm", "start"]